### ISSUE TITLE
Docker Creating Error

### ISSUE THREAD

**Issue by teawaterwu** [frankli0324/ctfd-whale#12]
1、按照这个教程完成CTFd+whale的安装https://github.com/frankli0324/ctfd-whale/blob/master/docs/install.md
2、使用教程中docker-compose.yml配置，访问whale插件发现报错：frpc admin api unauthorized，把docker-compose.yml中这两行注释掉
"--admin_user=frank",
"--admin_pwd=qwer",
发现不报错
3、然后添加challenges，使用常用的image ctftraining/qwb_2019_supersqli，这个镜像已经下载
```
root@lzpikgsx9zskgqdz-0829339:~/CTFd# docker image ls
REPOSITORY                       TAG               IMAGE ID       CREATED         SIZE
ctfd_ctfd                        latest            4a5f0f07a768   26 hours ago    662MB
0akarma-file-upload              latest            c55ff81bd155   3 days ago      433MB
webyuan                          latest            01f4f4de2334   3 days ago      747MB
python                           3.9-slim-buster   a90e142ad5dd   2 weeks ago     117MB
h1ve-main                        latest            a30bd8e04322   3 weeks ago     920MB
mariadb                          10.4              d8981e672fce   7 weeks ago     404MB
frankli0324/frp                  frps              afd08da9d951   2 months ago    14MB
frankli0324/frp                  frpc              70a284894ffc   2 months ago    12.4MB
nwdiag                           v4                bd9461dc32a5   4 months ago    651MB
ubuntu                           latest            54c9d81cbb44   5 months ago    72.8MB
grade                            v3                ce61896e6bef   11 months ago   400MB
mysql/mysql-server               latest            b24aaf2abddc   12 months ago   456MB
ubuntu                           14.04             13b66b487594   16 months ago   197MB
ubuntu                           trusty            13b66b487594   16 months ago   197MB
nginx                            1.17              9beeba249f3e   2 years ago     127MB
mariadb                          10.4.12           b6184b68d1fd   2 years ago     357MB
redis                            4                 191c4017dcdd   2 years ago     89.3MB
d0g3/h1ve                        latest            04a6ba2a504a   2 years ago     816MB
d0g3/h1ve-frp                    latest            5e0d10177d43   2 years ago     35.1MB
ctftraining/qwb_2019_supersqli   latest            36e6dfbba83f   2 years ago     379MB
php                              5.5-apache        ea0a3d41ce6c   5 years ago     390MB
```
4、启动challenges时报错
Docker Creation Error，
此时查看ctfd的logs发现
```traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/services/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/CTFd/CTFd/plugins/ctfd-whale/utils/control.py", line 15, in try_add_container
    DockerUtils.add_container(container)
  File "/opt/CTFd/CTFd/plugins/ctfd-whale/utils/docker.py", line 57, in add_container
    DockerUtils._create_standalone_container(DockerUtils.client, container)
  File "/opt/CTFd/CTFd/plugins/ctfd-whale/utils/docker.py", line 67, in _create_standalone_container
    client.services.create(
  File "/usr/local/lib/python3.9/site-packages/docker/models/services.py", line 225, in create
    service_id = self.client.api.create_service(**create_kwargs)
  File "/usr/local/lib/python3.9/site-packages/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/docker/api/service.py", line 189, in create_service
    return self._result(
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("network containers not found")

121.204.120.108 - - [27/Jul/2022:01:10:40 +0000] "POST /api/v1/plugins/ctfd-whale/container?challenge_id=3 HTTP/1.1" 403 55 "http://122.237.103.131:8000/challenges" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
```
请问要如何解决这个问题？不胜感激

**Comment by frankli0324** [comment]
> docker.errors.APIError: 500 Server Error: Internal Server Error ("network containers not found")

**Comment by teawaterwu** [comment]
> > docker.errors.APIError: 500 Server Error: Internal Server Error ("network containers not found")
> 
> btw，请正确使用markdown 又，移除admin user/pwd的时候请弄明白自己在干什么

非常感谢您的回复，因为完全不熟悉frpc，完全保留docker-compose.yml内容后访问ctfd的whale插件报错frpc admin api unauthorized，请问还需要做哪些方面的配置呢？

**Comment by frankli0324** [comment]
> If you are annoyed by the complicated configuration, and you just want to set bind_addr = 0.0.0.0, remember to enable Basic Auth included in frpc, and set API URL accordingly, for example, http://username:password@frpc:7400

也就是说，

**Comment by frankli0324** [comment]
请问问题是否已解决？

**Comment by teawaterwu** [comment]
> 请问问题是否已解决？
在ctfd控制台修改了这个
![1](https://user-images.githubusercontent.com/48787981/181169127-9008896f-ad6d-4942-8646-612ed9679933.jpg)

想问一下http://frank:qwer@frpc:7000/中的frpc是不是要用具体的ip替换？我查了docker，好像没看到7000端口
```
# docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS                 PORTS                                                                                  NAMES
cde140dbd6e7   frankli0324/frp:frpc   "/bin/frpc --server_…"   3 hours ago     Up 3 hours                                                                                                    ctfd_frpc_1
a43f9b34e289   frankli0324/frp:frps   "/bin/frps --bind_ad…"   30 hours ago    Up 30 hours            0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                              ctfd_frps_1
b8383f6c7e08   nginx:1.17             "nginx -g 'daemon of…"   30 hours ago    Up 30 hours            0.0.0.0:80->80/tcp, :::80->80/tcp                                                      ctfd_nginx_1
caae72862cbd   ctfd_ctfd              "/opt/CTFd/docker-en…"   30 hours ago    Up 30 hours            0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                              ctfd_ctfd_1
7926817eb34a   mariadb:10.4.12        "docker-entrypoint.s…"   30 hours ago    Up 30 hours                                                                                                   ctfd_db_1
76e9a56ce674   redis:4                "docker-entrypoint.s…"   30 hours ago    Up 30 hours                                                                                                   ctfd_cache_1
```

**Comment by frankli0324** [comment]
emmm你这不仅仅是不熟悉frpc啊，还不熟悉docker啊（瘫
同一个network内不需要publish port容器间也可以互访
倒是你设置的admin_user和pwd是啥就填啥啊，改完以后重启了么？docker-compose up了么？

**Comment by frankli0324** [comment]
由于不是ctfd-whale的原因，此issue关闭，如果仍然有需要帮助请发邮件
