### ISSUE TITLE
通过默认方式安装后插件启动报错

### ISSUE THREAD

**Issue by Nuyoooah** [frankli0324/ctfd-whale#15]
作者您好！按照安装指南操作，我在创建动态实例的时候出现了如下问题，请问有什么办法解决吗?

```traceback
ctfd_1   | ERROR [CTFd] Exception on /api/v1/challenges/2 [PATCH]
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
ctfd_1   |     rv = self.dispatch_request()
ctfd_1   |   File "/opt/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
ctfd_1   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ctfd_1   |   File "/opt/venv/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
ctfd_1   |     resp = resource(*args, **kwargs)
ctfd_1   |   File "/opt/venv/lib/python3.9/site-packages/flask/views.py", line 84, in view
ctfd_1   |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
ctfd_1   |   File "/opt/venv/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
ctfd_1   |     resp = meth(*args, **kwargs)
ctfd_1   |   File "/opt/CTFd/CTFd/utils/decorators/__init__.py", line 136, in admins_only_wrapper
ctfd_1   |     return f(*args, **kwargs)
ctfd_1   |   File "/opt/CTFd/CTFd/api/v1/challenges.py", line 466, in patch
ctfd_1   |     challenge = challenge_class.update(challenge, request)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/ctfd-whale/challenge_type.py", line 62, in update
ctfd_1   |     return DynamicValueChallenge.calculate_value(challenge)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/dynamic_challenges/__init__.py", line 53, in calculate_value
ctfd_1   |     f = DECAY_FUNCTIONS.get(challenge.function, logarithmic)
ctfd_1   | AttributeError: 'DynamicDockerChallenge' object has no attribute 'function'
```

**Comment by frankli0324** [comment]
简单确认了下，CTFd更新调整了题目模型结构，你可以先将CTFd仓库checkout到3.5.x版本使用，或者等我这两天调整一下插件

**Comment by frankli0324** [comment]
可以尝试feature/ctfd-3.6.x分支

**Comment by dsyzy** [comment]
view.js:3 Uncaught TypeError: CTFd.lib.markdown is not a function
    at view.js:3:46
（匿名） @ view.js:3
index.26ddae96.js:3 Uncaught (in promise) TypeError: o.preRender is not a function
    at index.26ddae96.js:3:1998
一直出现这样的问题，动态docker无法使用怎么办

**Comment by frankli0324** [comment]
@dsyzy 方便发下你的CTFd版本吗

**Comment by frankli0324** [comment]
@Nuyoooah 使用没问题的话麻烦反馈下，没问题我就合了

**Comment by dsyzy** [comment]
这个是参数传递的问题，后面我补充上

**Comment by frankli0324** [comment]
@dsyzy 如果和3.5到3.6版本的差异无关请开新的issue
